<div class="twelve columns alpha">
    <h3 class="headline">Descrição do Projeto</h3><span class="line"></span><div class="clearfix"></div>
    <p>Samba é um Software Livre sob a GNU General Public License, onde a primeira versão do código foi lançado em 1992 por Andrew Tridgell, de prestação de serviços SMB / CIFS protocolos de rede clientes de impressão e de arquivo. O nome do Samba comers de Server Message Block (SMB), o nome do protocolo padrão usado pelo sistema de arquivos Microsoft Windows Network.
	<p>Samba oferece compartilhamento de arquivos e impressoras entre computadores Windows e Unix executando permitindo a interoperabilidade entre eles. Ele implementa vários protocolos, incluindo os seguintes: NetBIOS sobre TCP / IP (NBT), SMB, CIFS, MSRPC, WINS Security Manager Contas (SAM) e autoridade de segurança local (LSA). O papel principal do Samba é a implementação de quatro serviços básicos modernos CIFS, que consiste de: Serviços de arquivo e impressão, autenticação e autorização, resolução de nomes, o anúncio de serviço.
	<p>A terceira versão (Samba3) não só fornece serviços de arquivo e impressão, mas também é capaz de integrar em um servidor de domínio do Windows, como um controlador de domínio primário (PDC) ou um membro de domínio em um sistema de domínio do Windows NT.
	<p>A versão 4 do samba (Samba4) foi a primeira implementação de Software Livre que foi compatível com os protocolos do Active Directory da Microsoft, onde protocolos do Active Directory são as principais implementações do serviço de diretório em administração de rede moderna. Samba 4 contém um servidor de diretório LDAP, servidor de autenticação Kerberos, um servidor DNS dinâmico seguro, e implementações de todas procedimento remoto necessário apela para Active Directory. Samba 4.0 oferece tudo o necessário para servir como um Active Directory Domain Controller Compatível para todas as versões do Microsoft
	<p>Clientes Windows atualmente suportado pela Microsoft, incluindo o recém-lançado Windows 8. O Samba 4 projeto que foi introduzido em CELTAB como uma demanda proveniente de Itaipu para cumprir a exigência de interoperabilidade entre os sistemas operacionais Unix e Windows. A principal preocupação é ter um sistema integrado que pode oferecer o controle total para o administrador do sistema para controlar os usuários MS-Windows em um ambiente Linux. Ter um servidor Samba trabalhar como um servidor de Active Directory irá satisfazer as suas necessidades para manter sob controle os arquivos e os usuários que estão integrados sob o seu domínio controlado. Para fornecer uma solução para esta situação, Celtab está elaborando um plano de migração para estabelecer a processo de migração inteiro, passo a passo, para conduzir 3700 usuários e seus desktops a partir de uma Samba 3 (NT Domain System) para ficar ao abrigo de um sistema de domínio do Active Directory com Samba 4.
    <p><strong>Pesquisadores:</strong> Aiman ​​Amin; Douglas Gatti; Arthur Garcete; Marcos Teixeira</p>
</div>
<!-- Job Description -->
<div class="four columns omega">
    <h3 class="headline">Detalhes do Projeto</h3><span class="line"></span><div class="clearfix"></div>
    <ul style="margin: 2px 0 18px 0;" class="list-3">
        <li>Infraestructura de Virtualización en ambiente de Texte/Homologación</li>
    </ul>
    <div class="clearfix"></div>
</div> 