<h3 class="headline">Quem Somos?</h3><span class="line" style="margin-bottom:30px;"></span><div class="clearfix"></div>
	<p><span class="dropcap">C</span>ELTAB é um centro de desenvolvimento de software livre e de código aberto, que começou com um acordo entre o Parque Tecnológico Itaipu (www.pti.org.br) e Itaipu Binacional (www.itaipu.gov.br).</p>
	<p>CELTAB também é um grupo de pesquisa e desenvolvimento na base computacional e a essência é a utilização e aperfeiçoamento de ferramentas e habilidades,  com a utilização de licenças livres e abertas.</p>
	<p>Temos também entre os nossos pesquisadores, pessoal qualificado para se comunicar plenamente nos seguintes idiomas: Português, Inglês, Espanhol, Alemão, Árabe e Guarani.</p>
	<p>O desenvolvimento de tecnologias livres e abertas na América Latina terá, a partir de agora, um importante aliado. A Itaipu Binacional e o Parque Tecnológico Itaipu (PTI) inauguraram o Centro Latino-Americano de Tecnologias Abertas (Celtab), que nasce com a proposta de ser um centro de pesquisa e de desenvolvimento de soluções inovadoras que utilizem exclusivamente tecnologias livres.</p>
	<p>Instalado no PTI, o Celtab conta com um investimento previsto de R$ 4,7 milhões para os próximos cinco anos. Ele atenderá, inicialmente, as demandas por tecnologia da Itaipu, do PTI e da região da Tríplice Fronteira (Argentina, Brasil e Paraguai). Posteriormente, as soluções desenvolvidas no Centro serão compartilhadas com os demais países da América Latina.</p>
	<p>A proposta do Celtab é criar uma rede de desenvolvimento colaborativo. “O foco não é a produção de software, mas sim a pesquisa de novas tecnologias. Nesta primeira fase, os protagonistas são a Itaipu e o PTI, mas já estamos buscando parcerias com as universidades da região e, no futuro, o Centro estará aberto a outras empresas que desejam investir em P&D de tecnologias abertas”.</p>
	<p>O Centro já conta com oito  pesquisadores, dois analistas e um consultor, que estão trabalhando em seis projetos de pesquisa, sendo quatro demandados pela Itaipu e dois pelo PTI. Um deles é o projeto de Biotelemetria, em que está sendo desenvolvida uma nova tecnologia, baseada em padrões abertos, para o controle automatizado dos peixes marcados com sensores que passam pelo Canal da Piracema. “Essa tecnologia substituirá um modelo proprietário e obsoleto que hoje atende parcialmente às necessidades da Itaipu e várias empresas do setor elétrico que realizam a marcação de peixes”.</p>
	<p>Além de incentivar e financiar a pesquisa científica de tecnologias abertas, a expectativa é que, no futuro, os projetos de P&D desenvolvidos no Centro possam gerar novos empreendimentos para a região. “Queremos atrair participantes sensibilizados para o empreendedorismo inovador, junto ao programa de Empreendedorismo do PTI, avaliando a viabilidade de incubação de novos negócios baseados no modelo de tecnologias abertas”.</p>
	<p><h3><span class="highlight color">Formação</span></h3></p>
	<p>A aproximação com as universidades da região também é uma estratégia do Centro. O intuito é levar para o ambiente acadêmico os processos de desenvolvimento de softwares de base livre. Serão apresentados, por exemplo, conceitos sobre como as comunidades se organizam e desenvolvem aplicativos livres.</p>
	<p>“É também um desejo do Celtab apresentar que o desenvolvimento de soluções com base de código livre, na forma de desenvolvimento colaborativo, está muito mais próximo dos primórdios da formação da computação do que muitos podem imaginar”. Usando o conceito de desenvolvimento colaborativo, o Celtab quer apresentar um paradigma de desenvolvimento que muito difere dos processos de criação de softwares proprietários.</p>
	<p>O principal software de código aberto desenvolvido no mundo e o maior em número de linhas de programação (tendo o LibreOffice como o segundo software com mais linhas de código) não segue nenhuma metodologia, seja ela qual for. Ele é construído de forma colaborativa. E como um software que não segue absolutamente nenhuma metodologia de desenvolvimento pode ser bem feito e apresentar tão baixa taxa de falhas? Esta é uma pergunta que as indústrias de software não conseguem responder e muito menos entender”.</p>
	<p><h3><span class="highlight color">Tecnologias livres e seus benefícios</span></h3></p>
	<p>Tecnologias livres e abertas são aquelas que podem ser usadas, copiadas, estudadas, modificadas e redistribuídas sem nenhuma restrição. Elas seguem um modelo de desenvolvimento baseado no compartilhamento, já que a solução é disponibilizada para que a comunidade possa usá-la e aprimorá-la. Dessa forma, cria-se um ciclo de desenvolvimento colaborativo, que favorece todos os envolvidos com o projeto e os usuários da solução.</p>
	<p>Além de fomentar o compartilhamento do conhecimento, a adoção e o investimento em tecnologias abertas também são uma opção estratégica para o avanço e para a domínio tecnológico, pois, por ser livre, uma solução pode ser usada e aprimorada sem depender da licença do seu fornecedor. “Esse compartilhamento de ideias e estudos é a base da ciência e gera um processo sinérgico de criação e inovação. Acreditamos que segredos e patentes só atrasam o desenvolvimento do conhecimento”.</p>
	<p><h3><span class="highlight color">Software livre na Itaipu e no PTI</span></h3>	</p>
	<p>O programa de utilização e desenvolvimento de software livre na Itaipu completou, em 2013, 10 anos. No escopo desse programa, foi criada a Conferência Latino-americana de Software Livre (Latinoware), que hoje é um dos maiores eventos de software livre da América Latina. Também já foram implantadas mais de 20 soluções open source na estrutura de TI da Itaipu, que atendem várias necessidades empresariais.</p>
	<p>O PTI também é exemplo no uso de software livre em ambiente corporativo. Atualmente, 100% da infraestrutura de serviços de e-mail, autenticação, controle de domínio, servidores de arquivos, telefonia e gerenciamento de rede é em software livre. Além disso, os programas e projetos também atuam no desenvolvimento de tecnologias abertas, como é o caso do Centro Internacional de Hidroinformática (CIH), que criou diversos sistemas de geoprocessamento baseados em software livre.</p>
	<p>“Com a criação do Celtab estamos dando um passo a mais e criando uma estrutura para pesquisa, desenvolvimento e melhoria de tecnologias abertas. Queremos criar soluções inovadoras e melhorar as já existentes para atender demandas da Itaipu e do PTI e também disponibilizá-las à comunidade latino-americana”.</p>
	<div class="clearfix"></div>
