<div class="twelve columns alpha">
    <h3 class="headline">Descripción del Proyecto</h3><span class="line"></span><div class="clearfix"></div>
    <p>Samba es un Software gratuito bajo la Licencia Pública General GNU, donde la primera versión del código fue lanzado en 1992 por Andrew Tridgell, para proporcionar servicios SMB / CIFS protocolos de red clientes de impresión y archivo. El nombre de Samba llegados de Server Message Block (SMB), el nombre del protocolo estándar utilizado por el sistema de archivos de Microsoft Windows Network.</p>
	<p>Samba ofrece compartir archivos e impresoras entre Windows y equipos con Unix que permite la interoperabilidad entre ellos. Implementa muchos protocolos incluiding los siguientes: NetBIOS sobre TCP / IP (NBT), SMB, CIFS, MSRPC, WINS, cuentas de seguridad (SAM) y la Autoridad de seguridad local (LSA). La función principal de Samba es implementar cuatro servicios básicos modernos CIFS, que incluye: servicios de archivo e impresión, autenticación y autorización, de resolución de nombres, del aviso de servicio.
	<p>La tercera versión (Samba3) no sólo proporciona servicios de archivos e impresión, pero también es capaz de integrarse en un dominio de Windows Server, como un controlador de dominio principal (PDC) o un miembro del dominio en un sistema de dominio de Windows NT.
	<p>La versión 4 de la samba (Samba4) fue la primera aplicación de software libre que fuera compatible con los protocolos de Active Directory de Microsoft, donde los protocolos de Active Directory son las principales implementaciones de servicios de directorio en la administración moderna red. Samba 4 contiene un servidor de directorio LDAP, servidor de autenticación Kerberos, el servidor DNS dinámico seguro, y las implementaciones de todo procedimiento remoto llama necesaria para Active Directory. Samba 4.0 ofrece todo lo necesario para servir de Active Directory Domain Controller compatible para todas las versiones de Microsoft
	<p>Los clientes de Windows soportadas actualmente por Microsoft, incluyendo Windows 8. El Samba 4 proyecto recientemente lanzado que fue introducido en CELTAB como una demanda proveniente de Itaipú para cumplir el requisito de la interoperabilidad entre los sistemas operativos Unix y Windows. La preocupación principal es tener un sistema integrado que puede ofrecer el control total para el administrador del sistema para el control de los usuarios de MS-Windows en un entorno Linux. Tener un servidor Samba a trabajar como servidor de Active Directory cumplirá sus necesidades para mantener bajo control los archivos y los usuarios que se integran bajo su dominio controlado. Para dar solución a esta situación, Celtab está elaborando un plan de migración para establecer con el proceso de migración de todo, paso a paso, para conducir 3700 usuarios y sus equipos de escritorio desde una Samba 3 (Sistema de Dominio NT) permanezcan bajo un Sistema de dominio de Active Directory con Samba 4.</p>
    <p><strong>Investigadores:</strong> Aiman ​​Amin; Douglas Gatti; Arthur Garcete; Marcos Teixeira</p>
</div>
<!-- Job Description -->
<div class="four columns omega">
    <h3 class="headline">Detalles del Proyecto</h3><span class="line"></span><div class="clearfix"></div>
    <ul style="margin: 2px 0 18px 0;" class="list-3">
        <li>Infraestructura de Virtualización en ambiente de Texte/Homologación</li>
    </ul>
    <div class="clearfix"></div>
</div> 